### ISSUE TITLE
Error loading plugin 'fastlane-plugin-browserstack' during run sparkfabrik/ios-build-action@v1.1.0

### ISSUE THREAD

**Issue by studium-inexorabile** [sparkfabrik/ios-build-action#5]
In attempting to utilize your action to build an iOS app, we received the following errors:

```
/usr/bin/bash /home/runner/work/_actions/sparkfabrik/ios-build-action/v1.1.0/dist/../build.sh
[21:50:01]: fastlane detected a Gemfile in the current directory
[21:50:01]: However, it seems like you didn't use `bundle exec`
[21:50:01]: To launch fastlane faster, please use
[21:50:01]: 
[21:50:01]: $ bundle exec fastlane export_ipa
[21:50:01]: 
[21:50:01]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[21:50:05]: Installing Ruby gem 'fastlane-plugin-browserstack'...
[21:50:06]: Error loading plugin 'fastlane-plugin-browserstack': You don't have write permissions for the /var/lib/gems/2.7.0 directory.
[21:50:06]: It seems like you wanted to load some plugins, however they couldn't be loaded
[21:50:06]: Please follow the troubleshooting guide: https://docs.fastlane.tools/plugins/plugins-troubleshooting/
+------------------------------+-----------+------------------+
|                        Used plugins                         |
+------------------------------+-----------+------------------+
| Plugin                       | Version   | Action           |
+------------------------------+-----------+------------------+
| fastlane-plugin-browserstack | undefined | No actions found |
+------------------------------+-----------+------------------+

[!] No actions were found while loading one or more plugins
    Please use `bundle exec fastlane` with plugins
    More info - https://docs.fastlane.tools/plugins/using-plugins/#run-with-plugins

[21:50:06]: Sending anonymous analytics information
[21:50:06]: Learn more at https://docs.fastlane.tools/#metrics
[21:50:06]: No personal or sensitive data is sent.
[21:50:06]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[21:50:06]: ------------------------------
[21:50:06]: --- Step: default_platform ---
[21:50:06]: ------------------------------
[21:50:06]: Driving the lane 'ios export_ipa' 🚀
[21:50:06]: -----------------------------
[21:50:06]: --- Step: create_keychain ---
[21:50:06]: -----------------------------
+------------------+----------------+
|           Lane Context            |
+------------------+----------------+
| DEFAULT_PLATFORM | ios            |
| PLATFORM_NAME    | ios            |
| LANE_NAME        | ios export_ipa |
+------------------+----------------+
[21:50:06]: Shell command exited with exit status 127 instead of 0.

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | create_keychain  | 0           |
+------+------------------+-------------+

[21:50:06]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Increment build number
    https://github.com/fastlane/fastlane/pull/127 [closed] 2 💬
    04 Feb 2017

➡️  fastlane notarize fails during staple even though the package is approved
    https://github.com/fastlane/fastlane/issues/17667 [open] 13 💬
    2 weeks ago

➡️  screengrab exiting with status 127 (FastlaneCore::Interface::FastlaneShellError)
    https://github.com/fastlane/fastlane/issues/15981 [closed] 2 💬
    18 Apr 2020

and 9 more at: https://github.com/fastlane/fastlane/search?q=Shell%20command%20exited%20with%20exit%20status%20127%20instead%20of%200.&type=Issues&utf8=✓


#######################################################################
# fastlane 2.188.0 is available. You are on 2.187.0.
# You should use the latest version.
# Please update using `gem install fastlane`.
#######################################################################
# Run `gem cleanup` from time to time to speed up fastlane
#######################################################################

2.188.0 Important fix for Apple ID auth
‼️ This is a must have update to fix some authentication issues for Apple ID Auth

* [spaceship] new team switching endpoint (#19132) via Josh Holtz
* [fastlane] bump addressable to >= 2.8 for patch security vulnerability (#19087) via Josh Holtz
* [action] gradle: Update for GRADLE_OUTPUT_JSON_OUTPUT_PATH and GRADLE… (#19038) via Bình Phạm
* [fastlane] added rubocop rule for no is_string in fastlane folder and actions (#19069) via Josh Holtz
* [fastlane][plugins] updated the ruby version in plugins' template (#19046) via Manish Rathi
* [screengrab] update dependencies and remove a jcenter dependency (#19020) via penn5
* [action] remove all instances of `is_string` in options and use `type` for appledoc (#19042), update_url_schemes (#19027), validate_play_store_json_key (#19030), version_get_podspec (#19031), upload_symbols_to_sentry (#19029), upload_app_privacy_details_to_app_store (#19028), xcode_server_get_assets (#19032), update_urban_airship_configuration (#19026), update_project_provisioning (#19025), update_plist (#19024), update_keychain_access_groups (#19023), update_info_plist (#19022), update_icloud_container_identifiers (#19021) via Manish Rathi


Please update using `gem install fastlane`
/usr/lib/ruby/2.7.0/rubygems/version.rb:215:in `initialize': Malformed version number string undefined (ArgumentError)
	from /usr/lib/ruby/2.7.0/rubygems/version.rb:206:in `new'
	from /usr/lib/ruby/2.7.0/rubygems/version.rb:206:in `new'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/plugins/plugin_update_manager.rb:29:in `block in show_update_status'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/plugins/plugin_update_manager.rb:26:in `each'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/plugins/plugin_update_manager.rb:26:in `show_update_status'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:44:in `ensure in start'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:54:in `start'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
/var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': \e[31m[!] Shell command exited with exit status 127 instead of 0.\e[0m (FastlaneCore::Interface::FastlaneShellError)
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/actions/create_keychain.rb:28:in `run'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:7:in `block (2 levels) in parsing_binding'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	from /var/lib/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /var/lib/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /var/lib/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /var/lib/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
/var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': Shell command exited with exit status 127 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/actions/create_keychain.rb:28:in `run'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:7:in `block (2 levels) in parsing_binding'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	from /var/lib/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /var/lib/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /var/lib/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /var/lib/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /var/lib/gems/2.7.0/gems/fastlane-2.187.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
Error: The process '/usr/bin/bash' failed with exit code 1
```

This is the `with` config used:
```
    project-path: ios/App/App.xcodeproj
    p12-base64: ***
    mobileprovision-base64: ***
    code-signing-identity: ***
    team-id: ***
    output-path: _removed for IP reasons_
    export-method: app-store
    configuration: Release
    build-pods: false
    pods-path: Podfile
    browserstack-upload: false
```

Our team has successfully utilized your other GH Action to build Android apps and we hope to utilize this one, as well.

Please let me know if there are any workarounds you're aware of or if you need more information about the environment/process that produced this error.

**Comment by edodusi** [comment]
Seems like it could't load the browserstack plugin. Will try myself and get back to you.

**Comment by jbuffin** [comment]
Hello, what was the resolution on this issue? We are currently having the same issue with the latest version.

**Comment by studium-inexorabile** [comment]
> Hello, what was the resolution on this issue? We are currently having the same issue with the latest version.

There was no resolution.

**Comment by jbuffin** [comment]
@edodusi Were you able to reproduce this issue? The ios-build-action is currently unusable as far as I can tell

**Comment by edodusi** [comment]
The issue with browserstack should be solved, testing the action I was able to get to the final task, be sure you are using the latest version, please feel free to open a PR if you find issues or improvements I would happily review them
